version: "3.9"
services:
  redis:
    image: redis
    ports:
      - 16379:6379
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    platform: linux/amd64
    build: .
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && foreman start"
    volumes:
      - .:/modern_rails_blog
    ports:
      - "3000:3000"
      - "35729:35279"
      - "40691:40691"
    depends_on:
      - db
