version: "3.9"
services:

  redis:
    image: redis
    ports:
      - 16379:6379
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    image: nginx
    ports:
      - "8080:443"
    volumes:
      - ./dev_web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dev_web/certs/nginx-selfsigned.crt:/etc/ssl/certs/example.com-rapidssl.crt
      - ./dev_web/certs/nginx-selfsigned.key:/etc/ssl/private/example.com-rapidssl.key

